### ISSUE TITLE
Missing processor information on Macbook Air

### ISSUE THREAD

**Issue by slanidjani** [AdamSzakal/specs-of-things#1]
Hello, I was about to fork this repo until i realised the processor information for the Macbook Air was missing. I'm currently in a state where I'm contemplating if I should still fork or creating something on my own. Is this repo still maintained? Just want to avoid divergence.

**Comment by AdamSzakal** [comment]
Processor Information (PI) is part of the next epic. It is mid-level prio, so it might take a while before dev resources manage to get it into a sprint. Please fork the repo and submit your PI updates for review (add at least 2 reviewers) and we'll merge it as soon as it passes all build tests.
